### ISSUE TITLE
Pregunta sobre el readme

### ISSUE THREAD

**Issue by jasba24** [RetaxMaster/RetaxMaster#1]
Hola bro, como hiciste el readme.md esta genial y como haces para que aparezca al inicio?

**Comment by RetaxMaster** [comment]
Es sintaxis Markdown, puedes usar cualquier editor que acepte Markdown para tener tu previsualización, cuando creas un repositorio en GitHub que contenga tu mismo nombre de usuario y que contenga un archivo README.md con el contenido Markdown que desees, esto lo detecta GitHub y automáticamente lo pone en tu inicio.

**Comment by jasba24** [comment]
ok bro muchas gracias tratare de hacer una descripcion tan pro como la tuya
